# Generated by Django 5.2.6 on 2025-09-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='intituleProd',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
    ]
