# Generated by Django 5.2.6 on 2025-09-04 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0003_contenir'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='dateFabrication',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.date.today),
        ),
    ]
