# Generated by Django 5.2.6 on 2025-09-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0004_produit_datefabrication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('idStatut', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=200)),
            ],
        ),
    ]
